export const CONFIG_FROALA = {
  entities: '',
  charCounterCount: true,
  charCounterMax: 100000,
  heightMin: '100%',
  heightMax: '100%',
  name: 'textarea',
  placeholderText: 'Nhập nội dung',
  pastePlain: true,
  pluginsEnabled: [
    'align',
    'charCounter',
    'codeBeautifier',
    'codeView',
    'colors',
    'draggable',
    'embedly',
    'emoticons',
    'entities',
    'file',
    'fontFamily',
    'fontSize',
    'fullscreen',
    'image',
    'imageManager',
    'inlineStyle',
    'lineBreaker',
    'link',
    'lists',
    'paragraphFormat',
    'paragraphStyle',
    // 'quickInsert',
    'quote',
    'save',
    'table',
    'url',
    'video',
    'wordPaste',
  ],
  // colorsHEXInput: false,
  autoFocus: true,
  toolbartop: true,
  // linkAlwaysBlank: true,
  fontFamilySelection: true,
  fontSizeSelection: true,
  paragraphFormatSelection: true,
  // htmlExecuteScripts: true,
  iframe: true,
  tabSpaces: 4,
  toolbarButtons: {
    moreText: {
      buttons: [
        'bold',
        'italic',
        'underline',
        'strikeThrough',
        'subscript',
        'superscript',
        'fontFamily',
        'fontSize',
        'textColor',
        'backgroundColor',
        'inlineClass',
        'inlineStyle',
        'clearFormatting',
      ],

      // Alignment of the group in the toolbar.
      // align: 'left',

      // By default, 3 buttons are shown in the main toolbar. The rest of them are available when using the more button.
      buttonsVisible: 5,
    },
    moreParagraph: {
      buttons: [
        'alignLeft',
        'alignCenter',
        'alignRight',
        'alignJustify',
        'outdent',
        'indent',
        'quote',
        'formatOLSimple',
        'formatOL',
        'formatUL',
        'paragraphFormat',
        'paragraphStyle',
        'lineHeight',
      ],
      // align: 'left',
      buttonsVisible: 7,
    },

    moreRich: {
      buttons: [
        'image',
        'insertLink',
        'insertTable',
        'insertImage',
        'insertVideo',
        'emoticons',
        'fontAwesome',
        'specialCharacters',
        'embedly',
        // 'insertFile',
        // 'insertHR',
      ],
      // align: 'left',
      buttonsVisible: 5,
    },

    moreMisc: {
      buttons: [
        'undo',
        'redo',
        'fullscreen',
        'print',
        'getPDF',
        'spellChecker',
        'selectAll',
        'html',
        'help',
      ],
      // align: 'right',
      buttonsVisible: 2,
    },
  },
};

export const CONFIG_SUN_EDITOR = {
  width: '100%',
  height: 'auto',
  charCounter: true,
  charCounterLabel: 'Characters :',
  maxCharCount: 100000,
  buttonList: [
    [
      'undo',
      'redo',
      'font',
      'fontSize',
      'formatBlock',
      'paragraphStyle',
      'blockquote',
      'bold',
      'underline',
      'italic',
      'strike',
      'subscript',
      'superscript',
      'fontColor',
      'hiliteColor',
      'textStyle',
      'removeFormat',
      'outdent',
      'indent',
      'align',
      'horizontalRule',
      'list',
      'lineHeight',
      'table',
      'link',
      // 'image',
      'customImage',
      'video',
      'audio' /** 'math', */, // You must add the 'katex' library at options to use the 'math' plugin. // You must add the "imageGalleryUrl".
      /** 'imageGallery', */ 'fullScreen',
      'showBlocks',
      'codeView',
      'preview',
      // 'print',
      // 'save',
      // 'template',
    ],
    // (min-width:992px)
    // [
    //   '%992',
    //   [
    //     ['pluginComamnd', 'undo', 'redo'],
    //     [
    //       ':p-More Paragraph-default.more_paragraph',
    //       'font',
    //       'fontSize',
    //       'formatBlock',
    //       'paragraphStyle',
    //       'blockquote',
    //     ],
    //     ['bold', 'underline', 'italic', 'strike'],
    //     [
    //       ':t-More Text-default.more_text',
    //       'subscript',
    //       'superscript',
    //       'fontColor',
    //       'hiliteColor',
    //       'textStyle',
    //     ],
    //     ['removeFormat'],
    //     ['outdent', 'indent'],
    //     ['align', 'horizontalRule', 'list', 'lineHeight'],
    //     [
    //       '-right',
    //       ':i-More Misc-default.more_vertical',
    //       'fullScreen',
    //       'showBlocks',
    //       'codeView',
    //       'preview',
    //       'print',
    //       'save',
    //       'template',
    //     ],
    //     [
    //       '-right',
    //       ':r-More Rich-default.more_plus',
    //       'table',
    //       'link',
    //       'image',
    //       'video',
    //       'audio',
    //       'math',
    //       'imageGallery',
    //     ],
    //   ],
    // ],
    // // (min-width:768px)
    // [
    //   '%768',
    //   [
    //     ['pluginComamnd', 'undo', 'redo'],
    //     [
    //       ':p-More Paragraph-default.more_paragraph',
    //       'font',
    //       'fontSize',
    //       'formatBlock',
    //       'paragraphStyle',
    //       'blockquote',
    //     ],
    //     [
    //       ':t-More Text-default.more_text',
    //       'bold',
    //       'underline',
    //       'italic',
    //       'strike',
    //       'subscript',
    //       'superscript',
    //       'fontColor',
    //       'hiliteColor',
    //       'textStyle',
    //       'removeFormat',
    //     ],
    //     [
    //       ':e-More Line-default.more_horizontal',
    //       'outdent',
    //       'indent',
    //       'align',
    //       'horizontalRule',
    //       'list',
    //       'lineHeight',
    //     ],
    //     [
    //       ':r-More Rich-default.more_plus',
    //       'table',
    //       'link',
    //       'image',
    //       'video',
    //       'audio',
    //       'math',
    //       'imageGallery',
    //     ],
    //     [
    //       '-right',
    //       ':i-More Misc-default.more_vertical',
    //       'fullScreen',
    //       'showBlocks',
    //       'codeView',
    //       'preview',
    //       'print',
    //       'save',
    //       'template',
    //     ],
    //   ],
    // ],
  ],
  placeholder: 'Start typing something...',
  imageUploadSizeLimit: 10000000,
  imageMultipleFile: true,
};
